/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package omar.cucumber.ingest.test

class Application {

    static void main(String[] args) {

        if (System.getenv("runEnv") == "local")
        {
            CucumberTest ingest = new CucumberTest()
            ingest.startTest()
        } else {
            TomcatStart tomcat = new TomcatStart()
            tomcat.startServer()
        }
    }
}